/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'id' : bigint,
  'status' : AnalysisStatus,
  'governingCheck' : string,
  'utilizationRatio' : number,
  'elementId' : bigint,
}
export type AnalysisStatus = { 'warning' : null } |
  { 'fail' : null } |
  { 'pass' : null };
export interface Clash {
  'id' : bigint,
  'resolved' : boolean,
  'element1Id' : bigint,
  'element2Id' : bigint,
  'clashType' : ClashType,
  'projectId' : bigint,
  'severity' : ClashSeverity,
}
export type ClashSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type ClashType = { 'workflow' : null } |
  { 'hard' : null } |
  { 'soft' : null };
export interface Comment {
  'id' : bigint,
  'resolved' : boolean,
  'createdAt' : bigint,
  'text' : string,
  'author' : string,
  'elementId' : bigint,
}
export interface Dimensions {
  'height' : number,
  'width' : number,
  'depth' : number,
}
export type Discipline = { 'mep' : null } |
  { 'structure' : null } |
  { 'architecture' : null } |
  { 'partsAssemblies' : null };
export interface Element {
  'id' : bigint,
  'discipline' : Discipline,
  'properties' : string,
  'projectId' : bigint,
  'position' : Position,
  'dimensions' : Dimensions,
  'elementType' : ElementType,
}
export type ElementType = { 'floor' : null } |
  { 'beam' : null } |
  { 'door' : null } |
  { 'duct' : null } |
  { 'pipe' : null } |
  { 'wall' : null } |
  { 'window' : null } |
  { 'column' : null };
export interface Position { 'x' : number, 'y' : number, 'z' : number }
export interface Project {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface Snapshot {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'projectId' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnalysisResult' : ActorMethod<
    [bigint, number, string, AnalysisStatus],
    bigint
  >,
  'addClash' : ActorMethod<
    [bigint, bigint, bigint, ClashType, ClashSeverity],
    bigint
  >,
  'addComment' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createElement' : ActorMethod<
    [bigint, ElementType, Discipline, string, Position, Dimensions],
    bigint
  >,
  'createProject' : ActorMethod<[string, string], bigint>,
  'createSnapshot' : ActorMethod<[bigint, string, string], bigint>,
  'getAllElementsByProject' : ActorMethod<[bigint], Array<Element>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAnalysesByElement' : ActorMethod<[bigint], Array<AnalysisResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClashesByProject' : ActorMethod<[bigint], Array<Clash>>,
  'getCommentsByElement' : ActorMethod<[bigint], Array<Comment>>,
  'getElement' : ActorMethod<[bigint], Element>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getSnapshotsByProject' : ActorMethod<[bigint], Array<Snapshot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveClash' : ActorMethod<[bigint], undefined>,
  'resolveComment' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];