/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisStatus = IDL.Variant({
  'warning' : IDL.Null,
  'fail' : IDL.Null,
  'pass' : IDL.Null,
});
export const ClashType = IDL.Variant({
  'workflow' : IDL.Null,
  'hard' : IDL.Null,
  'soft' : IDL.Null,
});
export const ClashSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ElementType = IDL.Variant({
  'floor' : IDL.Null,
  'beam' : IDL.Null,
  'door' : IDL.Null,
  'duct' : IDL.Null,
  'pipe' : IDL.Null,
  'wall' : IDL.Null,
  'window' : IDL.Null,
  'column' : IDL.Null,
});
export const Discipline = IDL.Variant({
  'mep' : IDL.Null,
  'structure' : IDL.Null,
  'architecture' : IDL.Null,
  'partsAssemblies' : IDL.Null,
});
export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const Dimensions = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
  'depth' : IDL.Float64,
});
export const Element = IDL.Record({
  'id' : IDL.Nat,
  'discipline' : Discipline,
  'properties' : IDL.Text,
  'projectId' : IDL.Nat,
  'position' : Position,
  'dimensions' : Dimensions,
  'elementType' : ElementType,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const AnalysisResult = IDL.Record({
  'id' : IDL.Nat,
  'status' : AnalysisStatus,
  'governingCheck' : IDL.Text,
  'utilizationRatio' : IDL.Float64,
  'elementId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Clash = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'element1Id' : IDL.Nat,
  'element2Id' : IDL.Nat,
  'clashType' : ClashType,
  'projectId' : IDL.Nat,
  'severity' : ClashSeverity,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Text,
  'elementId' : IDL.Nat,
});
export const Snapshot = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnalysisResult' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, AnalysisStatus],
      [IDL.Nat],
      [],
    ),
  'addClash' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, ClashType, ClashSeverity],
      [IDL.Nat],
      [],
    ),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createElement' : IDL.Func(
      [IDL.Nat, ElementType, Discipline, IDL.Text, Position, Dimensions],
      [IDL.Nat],
      [],
    ),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createSnapshot' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllElementsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Element)],
      ['query'],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAnalysesByElement' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AnalysisResult)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClashesByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Clash)], ['query']),
  'getCommentsByElement' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getElement' : IDL.Func([IDL.Nat], [Element], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getSnapshotsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Snapshot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveClash' : IDL.Func([IDL.Nat], [], []),
  'resolveComment' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisStatus = IDL.Variant({
    'warning' : IDL.Null,
    'fail' : IDL.Null,
    'pass' : IDL.Null,
  });
  const ClashType = IDL.Variant({
    'workflow' : IDL.Null,
    'hard' : IDL.Null,
    'soft' : IDL.Null,
  });
  const ClashSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ElementType = IDL.Variant({
    'floor' : IDL.Null,
    'beam' : IDL.Null,
    'door' : IDL.Null,
    'duct' : IDL.Null,
    'pipe' : IDL.Null,
    'wall' : IDL.Null,
    'window' : IDL.Null,
    'column' : IDL.Null,
  });
  const Discipline = IDL.Variant({
    'mep' : IDL.Null,
    'structure' : IDL.Null,
    'architecture' : IDL.Null,
    'partsAssemblies' : IDL.Null,
  });
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const Dimensions = IDL.Record({
    'height' : IDL.Float64,
    'width' : IDL.Float64,
    'depth' : IDL.Float64,
  });
  const Element = IDL.Record({
    'id' : IDL.Nat,
    'discipline' : Discipline,
    'properties' : IDL.Text,
    'projectId' : IDL.Nat,
    'position' : Position,
    'dimensions' : Dimensions,
    'elementType' : ElementType,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const AnalysisResult = IDL.Record({
    'id' : IDL.Nat,
    'status' : AnalysisStatus,
    'governingCheck' : IDL.Text,
    'utilizationRatio' : IDL.Float64,
    'elementId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Clash = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'element1Id' : IDL.Nat,
    'element2Id' : IDL.Nat,
    'clashType' : ClashType,
    'projectId' : IDL.Nat,
    'severity' : ClashSeverity,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Text,
    'elementId' : IDL.Nat,
  });
  const Snapshot = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnalysisResult' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, AnalysisStatus],
        [IDL.Nat],
        [],
      ),
    'addClash' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, ClashType, ClashSeverity],
        [IDL.Nat],
        [],
      ),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createElement' : IDL.Func(
        [IDL.Nat, ElementType, Discipline, IDL.Text, Position, Dimensions],
        [IDL.Nat],
        [],
      ),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createSnapshot' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllElementsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Element)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAnalysesByElement' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AnalysisResult)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClashesByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Clash)], ['query']),
    'getCommentsByElement' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getElement' : IDL.Func([IDL.Nat], [Element], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getSnapshotsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Snapshot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveClash' : IDL.Func([IDL.Nat], [], []),
    'resolveComment' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };