/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Comment {
    id: bigint;
    resolved: boolean;
    createdAt: bigint;
    text: string;
    author: string;
    elementId: bigint;
}
export interface Position {
    x: number;
    y: number;
    z: number;
}
export interface Clash {
    id: bigint;
    resolved: boolean;
    element1Id: bigint;
    element2Id: bigint;
    clashType: ClashType;
    projectId: bigint;
    severity: ClashSeverity;
}
export interface Snapshot {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    projectId: bigint;
}
export interface Dimensions {
    height: number;
    width: number;
    depth: number;
}
export interface Project {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}
export interface Element {
    id: bigint;
    discipline: Discipline;
    properties: string;
    projectId: bigint;
    position: Position;
    dimensions: Dimensions;
    elementType: ElementType;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface AnalysisResult {
    id: bigint;
    status: AnalysisStatus;
    governingCheck: string;
    utilizationRatio: number;
    elementId: bigint;
}
export enum AnalysisStatus {
    warning = "warning",
    fail = "fail",
    pass = "pass"
}
export enum ClashSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum ClashType {
    workflow = "workflow",
    hard = "hard",
    soft = "soft"
}
export enum Discipline {
    mep = "mep",
    structure = "structure",
    architecture = "architecture",
    partsAssemblies = "partsAssemblies"
}
export enum ElementType {
    floor = "floor",
    beam = "beam",
    door = "door",
    duct = "duct",
    pipe = "pipe",
    wall = "wall",
    window_ = "window",
    column = "column"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnalysisResult(elementId: bigint, utilizationRatio: number, governingCheck: string, status: AnalysisStatus): Promise<bigint>;
    addClash(projectId: bigint, element1Id: bigint, element2Id: bigint, clashType: ClashType, severity: ClashSeverity): Promise<bigint>;
    addComment(elementId: bigint, author: string, text: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createElement(projectId: bigint, elementType: ElementType, discipline: Discipline, properties: string, position: Position, dimensions: Dimensions): Promise<bigint>;
    createProject(name: string, description: string): Promise<bigint>;
    createSnapshot(projectId: bigint, name: string, description: string): Promise<bigint>;
    getAllElementsByProject(projectId: bigint): Promise<Array<Element>>;
    getAllProjects(): Promise<Array<Project>>;
    getAnalysesByElement(elementId: bigint): Promise<Array<AnalysisResult>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClashesByProject(projectId: bigint): Promise<Array<Clash>>;
    getCommentsByElement(elementId: bigint): Promise<Array<Comment>>;
    getElement(elementId: bigint): Promise<Element>;
    getProject(projectId: bigint): Promise<Project>;
    getSnapshotsByProject(projectId: bigint): Promise<Array<Snapshot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resolveClash(clashId: bigint): Promise<void>;
    resolveComment(commentId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProject(projectId: bigint, name: string, description: string): Promise<void>;
}
import type { AnalysisResult as _AnalysisResult, AnalysisStatus as _AnalysisStatus, Clash as _Clash, ClashSeverity as _ClashSeverity, ClashType as _ClashType, Dimensions as _Dimensions, Discipline as _Discipline, Element as _Element, ElementType as _ElementType, Position as _Position, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnalysisResult(arg0: bigint, arg1: number, arg2: string, arg3: AnalysisStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnalysisResult(arg0, arg1, arg2, to_candid_AnalysisStatus_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnalysisResult(arg0, arg1, arg2, to_candid_AnalysisStatus_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addClash(arg0: bigint, arg1: bigint, arg2: bigint, arg3: ClashType, arg4: ClashSeverity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClash(arg0, arg1, arg2, to_candid_ClashType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_ClashSeverity_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClash(arg0, arg1, arg2, to_candid_ClashType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_ClashSeverity_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createElement(arg0: bigint, arg1: ElementType, arg2: Discipline, arg3: string, arg4: Position, arg5: Dimensions): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createElement(arg0, to_candid_ElementType_n9(this._uploadFile, this._downloadFile, arg1), to_candid_Discipline_n11(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createElement(arg0, to_candid_ElementType_n9(this._uploadFile, this._downloadFile, arg1), to_candid_Discipline_n11(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createSnapshot(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSnapshot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSnapshot(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllElementsByProject(arg0: bigint): Promise<Array<Element>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllElementsByProject(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllElementsByProject(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAnalysesByElement(arg0: bigint): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysesByElement(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysesByElement(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClashesByProject(arg0: bigint): Promise<Array<Clash>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClashesByProject(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClashesByProject(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsByElement(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByElement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByElement(arg0);
            return result;
        }
    }
    async getElement(arg0: bigint): Promise<Element> {
        if (this.processError) {
            try {
                const result = await this.actor.getElement(arg0);
                return from_candid_Element_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElement(arg0);
            return from_candid_Element_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return result;
        }
    }
    async getSnapshotsByProject(arg0: bigint): Promise<Array<Snapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSnapshotsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSnapshotsByProject(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resolveClash(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveClash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveClash(arg0);
            return result;
        }
    }
    async resolveComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveComment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AnalysisResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisStatus): AnalysisStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ClashSeverity_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClashSeverity): ClashSeverity {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ClashType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClashType): ClashType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Clash_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Clash): Clash {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Discipline_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Discipline): Discipline {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ElementType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElementType): ElementType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Element_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Element): Element {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    discipline: _Discipline;
    properties: string;
    projectId: bigint;
    position: _Position;
    dimensions: _Dimensions;
    elementType: _ElementType;
}): {
    id: bigint;
    discipline: Discipline;
    properties: string;
    projectId: bigint;
    position: Position;
    dimensions: Dimensions;
    elementType: ElementType;
} {
    return {
        id: value.id,
        discipline: from_candid_Discipline_n16(_uploadFile, _downloadFile, value.discipline),
        properties: value.properties,
        projectId: value.projectId,
        position: value.position,
        dimensions: value.dimensions,
        elementType: from_candid_ElementType_n18(_uploadFile, _downloadFile, value.elementType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AnalysisStatus;
    governingCheck: string;
    utilizationRatio: number;
    elementId: bigint;
}): {
    id: bigint;
    status: AnalysisStatus;
    governingCheck: string;
    utilizationRatio: number;
    elementId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AnalysisStatus_n23(_uploadFile, _downloadFile, value.status),
        governingCheck: value.governingCheck,
        utilizationRatio: value.utilizationRatio,
        elementId: value.elementId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    element1Id: bigint;
    element2Id: bigint;
    clashType: _ClashType;
    projectId: bigint;
    severity: _ClashSeverity;
}): {
    id: bigint;
    resolved: boolean;
    element1Id: bigint;
    element2Id: bigint;
    clashType: ClashType;
    projectId: bigint;
    severity: ClashSeverity;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        element1Id: value.element1Id,
        element2Id: value.element2Id,
        clashType: from_candid_ClashType_n31(_uploadFile, _downloadFile, value.clashType),
        projectId: value.projectId,
        severity: from_candid_ClashSeverity_n33(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mep: null;
} | {
    structure: null;
} | {
    architecture: null;
} | {
    partsAssemblies: null;
}): Discipline {
    return "mep" in value ? Discipline.mep : "structure" in value ? Discipline.structure : "architecture" in value ? Discipline.architecture : "partsAssemblies" in value ? Discipline.partsAssemblies : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    floor: null;
} | {
    beam: null;
} | {
    door: null;
} | {
    duct: null;
} | {
    pipe: null;
} | {
    wall: null;
} | {
    window: null;
} | {
    column: null;
}): ElementType {
    return "floor" in value ? ElementType.floor : "beam" in value ? ElementType.beam : "door" in value ? ElementType.door : "duct" in value ? ElementType.duct : "pipe" in value ? ElementType.pipe : "wall" in value ? ElementType.wall : "window" in value ? ElementType.window : "column" in value ? ElementType.column : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    fail: null;
} | {
    pass: null;
}): AnalysisStatus {
    return "warning" in value ? AnalysisStatus.warning : "fail" in value ? AnalysisStatus.fail : "pass" in value ? AnalysisStatus.pass : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workflow: null;
} | {
    hard: null;
} | {
    soft: null;
}): ClashType {
    return "workflow" in value ? ClashType.workflow : "hard" in value ? ClashType.hard : "soft" in value ? ClashType.soft : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): ClashSeverity {
    return "low" in value ? ClashSeverity.low : "high" in value ? ClashSeverity.high : "critical" in value ? ClashSeverity.critical : "medium" in value ? ClashSeverity.medium : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Element>): Array<Element> {
    return value.map((x)=>from_candid_Element_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisResult>): Array<AnalysisResult> {
    return value.map((x)=>from_candid_AnalysisResult_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Clash>): Array<Clash> {
    return value.map((x)=>from_candid_Clash_n29(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisStatus): _AnalysisStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ClashSeverity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClashSeverity): _ClashSeverity {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ClashType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClashType): _ClashType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Discipline_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Discipline): _Discipline {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ElementType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementType): _ElementType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElementType): {
    floor: null;
} | {
    beam: null;
} | {
    door: null;
} | {
    duct: null;
} | {
    pipe: null;
} | {
    wall: null;
} | {
    window: null;
} | {
    column: null;
} {
    return value == ElementType.floor ? {
        floor: null
    } : value == ElementType.beam ? {
        beam: null
    } : value == ElementType.door ? {
        door: null
    } : value == ElementType.duct ? {
        duct: null
    } : value == ElementType.pipe ? {
        pipe: null
    } : value == ElementType.wall ? {
        wall: null
    } : value == ElementType.window ? {
        window_: null
    } : value == ElementType.column ? {
        column: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Discipline): {
    mep: null;
} | {
    structure: null;
} | {
    architecture: null;
} | {
    partsAssemblies: null;
} {
    return value == Discipline.mep ? {
        mep: null
    } : value == Discipline.structure ? {
        structure: null
    } : value == Discipline.architecture ? {
        architecture: null
    } : value == Discipline.partsAssemblies ? {
        partsAssemblies: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisStatus): {
    warning: null;
} | {
    fail: null;
} | {
    pass: null;
} {
    return value == AnalysisStatus.warning ? {
        warning: null
    } : value == AnalysisStatus.fail ? {
        fail: null
    } : value == AnalysisStatus.pass ? {
        pass: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClashType): {
    workflow: null;
} | {
    hard: null;
} | {
    soft: null;
} {
    return value == ClashType.workflow ? {
        workflow: null
    } : value == ClashType.hard ? {
        hard: null
    } : value == ClashType.soft ? {
        soft: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClashSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == ClashSeverity.low ? {
        low: null
    } : value == ClashSeverity.high ? {
        high: null
    } : value == ClashSeverity.critical ? {
        critical: null
    } : value == ClashSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
